id: A0689006C
title: The Prayer to Swiftly Fulfil All Wishes
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 22:54:24.366442
  last_modified_at: 2022-02-28 22:54:24.366445
