id: A0689006C
title: 'The Lotus of Faith: A Supplication to the Successive Lives of Shechen Rabjam'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 22:54:24.361605
  last_modified_at: 2022-02-28 22:54:24.361611
