id: A0689006C
title: Lamenting Prayer to Jamyang Chökyi Lodrö
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 22:54:24.335608
  last_modified_at: 2022-02-28 22:54:24.335614
