id: A0689006C
title: 'The Blissful Path to the Ocean of Bodhichitta: A Brief Prayer of Aspiration
  for Mind Training'
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-02-28 22:54:24.358179
  last_modified_at: 2022-02-28 22:54:24.358182
