id: A0689006C
title: 'The Vajra Sitar of Immortality: A Prayer for the Long Life of the Fourth Incarnation
  of Terchen Chokgyur Lingpa'
type: translation
source_metadata:
  languages:
  - en
  - es
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-02-28 22:54:24.375722
  last_modified_at: 2022-02-28 22:54:24.375725
