id: A0689006C
title: 'Light of Compassion: A Prayer to the Wisdom Ḍākinīs'
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-02-28 22:54:24.338129
  last_modified_at: 2022-02-28 22:54:24.338132
