id: A0689006C
title: Concise Offering of the Body from the Root Text of the Heart Accomplishment
  of the Guru Tukdrup, The Essential Manual of Oral Instructions (Shaldam Nyingjang)
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 22:54:24.321171
  last_modified_at: 2022-02-28 22:54:24.321175
