id: A0689006C
title: 'True Words to Accomplish Immortality: A Longevity Prayer to the Tulku of Jamyang
  Khyentse, Thupten Chökyi Gyatso'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 22:54:24.378848
  last_modified_at: 2022-02-28 22:54:24.378851
