id: A0689006C
title: Prayer for the Long Life of Dzongsar Jamyang Khyentse Rinpoche
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 22:54:24.345762
  last_modified_at: 2022-02-28 22:54:24.345765
