id: A0689006C
title: 'Wisdom''s Melody: An Aspiration to Realize Madhyamaka, Mahāmudrā, and Mahā
  Ati'
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-02-28 22:54:24.383625
  last_modified_at: 2022-02-28 22:54:24.383630
