id: A0689006C
title: Prayer for the Long Life of Shechen Rabjam Rinpoche
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - it
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-02-28 22:54:24.347747
  last_modified_at: 2022-02-28 22:54:24.347750
