id: A0689006C
title: 'A Garland of Vajra Words: A Prayer to the Guru'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 22:54:24.290653
  last_modified_at: 2022-02-28 22:54:24.290689
