id: A0689006C
title: Calling the Guru from Afar
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 22:54:24.317774
  last_modified_at: 2022-02-28 22:54:24.317781
