id: A0689006C
title: 'Guru Yoga: The Complete Path of Sūtra And Tantra'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 22:54:24.326869
  last_modified_at: 2022-02-28 22:54:24.326872
