id: A0689006C
title: Prayer to Longchenpa (Adapted from the Words of Mipham Rinpoche)
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-02-28 22:54:24.350898
  last_modified_at: 2022-02-28 22:54:24.350901
