id: A0689006C
title: 'The Vidyādharas'' Words of Truth: An Aspiration Connected with the Stages
  of the Path of the Three Roots, from the Heart Essence of the Vast Expanse'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 22:54:24.377514
  last_modified_at: 2022-02-28 22:54:24.377517
