id: A0689006C
title: 'Vajrakīla Prayer: A Rain of Accomplishments'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 22:54:24.380622
  last_modified_at: 2022-02-28 22:54:24.380625
