id: A0689006C
title: 'The Potent Nectar of Accomplishment: A Prayer and Supplication to the VidyÄdhara
  Gurus of the Three Lineages'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 22:54:24.364155
  last_modified_at: 2022-02-28 22:54:24.364158
