id: A0689006C
title: Daily Practice of Guru Rinpoche, Buddha of Medicine
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 22:54:24.322235
  last_modified_at: 2022-02-28 22:54:24.322238
