id: A0689006C
title: Concise Daily Practice of Vajrasattva
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 22:54:24.319614
  last_modified_at: 2022-02-28 22:54:24.319619
