id: A0689006C
title: 'The Precious Jewel Essence: A Prayer of the Four Dharmas'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 22:54:24.367545
  last_modified_at: 2022-02-28 22:54:24.367548
