id: A0689006C
title: Invocation of the Vidyādhara Gurus
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 22:54:24.332552
  last_modified_at: 2022-02-28 22:54:24.332566
