id: A0689006C
title: 'Nectar Shower of Blessings: A Song of Yearning Devotion Recalling the Everpresent
  Gurus'
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-02-28 22:54:24.341430
  last_modified_at: 2022-02-28 22:54:24.341433
