id: A0689006C
title: Supplication to the Lineage of the Heart Essence of the Vast Expanse
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 22:54:24.354630
  last_modified_at: 2022-02-28 22:54:24.354633
