id: A0689006C
title: 'All Wishes Swiftly Fulfilled: A Prayer to the Mahāguru of Uḍḍiyāna in Eight
  Chapters'
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-02-28 22:54:24.309346
  last_modified_at: 2022-02-28 22:54:24.309349
