id: A0689006C
title: A Prayer to Dilgo Khyentse Rinpoche
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 22:54:24.294704
  last_modified_at: 2022-02-28 22:54:24.294723
