id: A0689006C
title: 'Beautiful Clouds of Blessings: A Prayer to the Lineage Masters of the Heart
  Essence of the Vast Expanse from the Great Perfection'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 22:54:24.312009
  last_modified_at: 2022-02-28 22:54:24.312012
