id: A0689006C
title: 'The Swift Bestowal of Blessings: A Prayer to the Glorious Protector Guru'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 22:54:24.373741
  last_modified_at: 2022-02-28 22:54:24.373743
