id: A0689006C
title: Prayer for the Fulfilment of Aspirations
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - it
  - nl
  - bo
  datatype: PlainText
  created_at: 2022-02-28 22:54:24.344173
  last_modified_at: 2022-02-28 22:54:24.344177
