id: A0689006C
title: Heart Advice in Four Lines
type: translation
source_metadata:
  languages:
  - en
  - es
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-02-28 22:54:24.329121
  last_modified_at: 2022-02-28 22:54:24.329124
