id: A0689006C
title: 'Shower of Indestructible Splendour: A Self-Initiation for the Guru Practice
  of the VidyÄdhara Assembly, from the Heart-Essence of the Vast Expanse'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 22:54:24.353025
  last_modified_at: 2022-02-28 22:54:24.353028
