id: A0689006C
title: 'The Refined Essence of Compassion: A Daily Sādhana for the Natural Liberation
  of Suffering, the Secret Practice of the Great Compassionate One'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 22:54:24.370847
  last_modified_at: 2022-02-28 22:54:24.370850
