id: A0689006C
title: Prayer to Khandro Tsering Chödrön
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 22:54:24.349053
  last_modified_at: 2022-02-28 22:54:24.349057
